<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1f6d84d7327d9d8454c4104dd2c6bfd7
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WP_FUNDI_BLOCKS\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WP_FUNDI_BLOCKS\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1f6d84d7327d9d8454c4104dd2c6bfd7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1f6d84d7327d9d8454c4104dd2c6bfd7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1f6d84d7327d9d8454c4104dd2c6bfd7::$classMap;

        }, null, ClassLoader::class);
    }
}
